version: '3.8'
services:
  openwebrx:
    build: .
    container_name: openwebrx
    hostname: openwebrx
    restart: always
    cap_add:
      - "SYS_RAWIO"
      - "SYS_ADMIN"
      - "SYS_RESOURCE"
      - "SYS_MODULE"
    volumes:
      - ./openwebrx/data:/var/lib/openwebrx
      - ./openwebrx/config:/etc/openwebrx
      - ./openwebrx/plugins:/opt/openwebrx/htdocs/plugins
      - /dev:/dev:rwm
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - type: tmpfs
        target: /tmp
        tmpfs:
          mode: 01777
    devices:
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - 8073:8073

